### PR TITLE
Use jemallocator

### PR DESCRIPTION
**Pull request by Razican**
I have changed the system allocator for Jemallocator as the global allocator for the binary and the benchmarks. Jemalloc makes the binary bigger, but the performance should increase nicely, which is something we probably want in a compiler.

My benchmarks show around 10% improvement or more in some cases.

### CODE REVIEW

**Comment by jasonwilliams** [comment]
What’s the reason Jemallocator makes the binaries bigger?
(I know very little about jemalloc)

**Comment by jasonwilliams** [comment]
Why are the benchmarks stuck hmm

**Comment by Razican** [comment]
I cancelled, but it seems I cannot run it again. Still, it seems it passed two times, right?

**Comment by Razican** [comment]
Should we merge this?

**Pull request merged**
