### PR TITLE
WIP - Update JSON Global

### PR DESCRIPTION
**Pull request by DomParfitt**
Updates the JSON object to be consistent with other global objects per #128.

@jasonwilliams are you able to have a quick look and let me know if I'm on the right track? I've been using the existing code and the ECMA spec for the [JSON object](https://tc39.es/ecma262/#sec-json-object) but I'm not hugely familiar with the ES internals.

### CODE REVIEW

**Comment by jasonwilliams** [comment]
I've made some changes to the benchmarks Action, could you try rebasing and pushing again?

**Comment by DomParfitt** [comment]
Thanks @jasonwilliams, I've rebased the changes from the upstream onto my branch but it seems that the benchmarks are still failing. I'm not really sure where to start looking for this.

**Comment by DomParfitt** [comment]
Also, I was considering doing the change for each global as its own PR just so they're a bit more digestible. Are you happy for me to do it this way or would you rather they all be done as a single PR?

**Comment by jasonwilliams** [comment]
yeah, that makes sense

**Comment by jasonwilliams** [comment]
@DomParfitt looking good, im not sure if you need to rebase, some changes in there i think are merged now

**Pull request merged**
