### PR TITLE
WIP: Create constant values via the prototype constructor

### LINKED ISSUE #210: builtinfun.length undefined
I'm getting `undefined` when I do `'abc'.matchAll.length`. This is incompatible with Chrome's implementation (for example), where I get `1`.

Testing with master with the following `tests.js`:

```js
console.log('abc'.matchAll.length);
```

Here's the output for `cargo run`:

```
$ cargo run
   Compiling Boa v0.5.0 (/data/boa)
    Finished dev [unoptimized + debuginfo] target(s) in 3.20s
     Running `target/debug/boa`
undefined
[src/bin/bin.rs:57] exec(&buffer) = "undefined"
```

Related to #193 and #206

### PR DESCRIPTION
**Pull request by Stupremee**
This Pull Request changes the evaluation of `Const` values (Num, Bool, String) to use the specific prototype constructor to set all required properties and methods.

Resolves #210

### CODE REVIEW

**Comment by Stupremee** [comment]
I ran into more issues, if a number value gets converted to an object, the `to_num` method doesn't work and so all `BinOp` operations are not working correctly.

**Comment by jasonwilliams** [comment]
@Stupremee won't this create Object instances instead of native types?
```js
let a = 1;
typeof 1; // object
```

on your branch

**Comment by Stupremee** [comment]
Yep, that's the problem I didn't think about that earlier.

**Comment by Razican** [comment]
Hello, what is the state of this?

**Comment by jasonwilliams** [comment]
I'm going to close this PR as its quite outdated now

**Pull request closed without merging**
