### PR TITLE
unassigned var is undefined

### LINKED ISSUE #113: Unassigned variables have default of null instead of undefined
The following statements both print `null` instead of `undefined`.

```js
var x;
x;
```
and
```js
let x;
x;
```

Testing locally, it seems like it's enough to change the defaults at https://github.com/jasonwilliams/boa/blob/8851eba27d1df86e139e101f2b0ce26dbf3a1920/src/lib/exec.rs#L395 and https://github.com/jasonwilliams/boa/blob/8851eba27d1df86e139e101f2b0ce26dbf3a1920/src/lib/exec.rs#L407

to `ValueData::Undefined`.

### PR DESCRIPTION
**Pull request by pop**
Fixes #113 

Just like the original issue claimed, this was a two line fix...

... but I didn't stop there! I don't feel comfortable making a change without tests, so I built out the `tests/js/test.js` file to (A) include a test for my fix and (B) include some scaffolding for future JS smoke tests.

If you think this needs some changes, feel free to ping me or make some commits on my branch. I'd also be willing to remove the testing changes. They don't really "fit" in this pull request and I'd understand if you are philosophically opposed to them.

### CODE REVIEW

**Comment by pop** [comment]
@jasonwilliams Good to know! I added two tests to the bottom of `exec.rs`.

Let me know if you want me to remove the changes to `tests/js/test.js`, or if you want me to add something to the CHANGELOG for this. And of course any other changes you'd like.

**Comment by jasonwilliams** [comment]
@pop if you could update the CHANGELOG and revert the test.js changes that would be great

**Comment by jasonwilliams** [comment]
@pop sorry ive merged since so you may need to rebase

**Comment by pop** [comment]
@jasonwilliams I think it's ready :smile: 

Added some CHANGELOG text, removed my tests/js/test.js code and added a comment to that file to help future me, and fixed my tests.

**Pull request merged**
