### PR TITLE
Fixed compilation without "wasm-bindgen" feature

### LINKED ISSUE #234: Unable to compile without "wasm-bindgen" feature
Currently, wasm-bindgen is listed in the `Cargo.toml` as:
```
# Optional Dependencies
wasm-bindgen = { version = "^0.2.50", optional = true }
```
and set as a default dependency. However disabling this dependency with:
```
Boa = { version = "0.5.1", default-features = false }
```
leads to the errors: 
```
error[E0433]: failed to resolve: use of undeclared type or module `wasm_bindgen`
  --> C:\Users\nathaniel\.cargo\registry\src\github.com-1ecc6299db9ec823\Boa-0.5.1\src/lib/lib.rs:48:5
   |
48 | use wasm_bindgen::prelude::*;
   |     ^^^^^^^^^^^^ use of undeclared type or module `wasm_bindgen`

error: cannot find attribute `wasm_bindgen` in this scope
  --> C:\Users\nathaniel\.cargo\registry\src\github.com-1ecc6299db9ec823\Boa-0.5.1\src/lib/lib.rs:88:3
   |
88 | #[wasm_bindgen]
   |   ^^^^^^^^^^^^

error: cannot find attribute `wasm_bindgen` in this scope
  --> C:\Users\nathaniel\.cargo\registry\src\github.com-1ecc6299db9ec823\Boa-0.5.1\src/lib/lib.rs:92:7
   |
92 |     #[wasm_bindgen(js_namespace = console)]
   |       ^^^^^^^^^^^^

error: cannot find attribute `wasm_bindgen` in this scope
  --> C:\Users\nathaniel\.cargo\registry\src\github.com-1ecc6299db9ec823\Boa-0.5.1\src/lib/lib.rs:96:3
   |
96 | #[wasm_bindgen]
   |   ^^^^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `Boa`.
```
as the wasm_bindgen proc-macro is still used even while the dependency is disabled. I think this should probably be fixed by putting the wasm interface in its own module and conditionally compiling it.

### PR DESCRIPTION
**Pull request by adumbidiot**
Fixes #234. I put the wasm-related stuff in its own module. I also conditionally re-exported the contents of this module, as the `evaluate` function is public and I was unsure if making it private would break semver.

### CODE REVIEW

**Comment by adumbidiot** [comment]
The CI error seems unrelated?

**Comment by Razican** [comment]
CI error is due to the update in `clippy` for Rust 1.41, that now requires an `Errors` section in the documentation of functions returning a `Result<_, _>` with `pedantic` lints.

**Comment by jasonwilliams** [comment]
@Razican eugh, i thought we switched "pedantic" errors off, that lint looks like it falls under the "pedantic" group.

maybe the wasm file needs to copy https://github.com/jasonwilliams/boa/blob/master/src/lib/lib.rs#L2-L4

**Comment by jasonwilliams** [comment]
could you rebase @adumbidiot ? ive merged some clippy fixes

**Comment by adumbidiot** [comment]
@jasonwilliams done

**Pull request merged**
