### PR TITLE
Dependency upgrade

### PR DESCRIPTION
**Pull request by Razican**
I upgraded all dependencies both for our wasm demo and for our core in Rust. This (with some potential extra upgrades until the release) should get merged for 0.8.

### CODE REVIEW

**Comment by Razican** [comment]
I found 3 issues with this:
 - `text-encoding` is [deprecated](https://www.npmjs.com/package/text-encoding), we should use [`fast-text-encoding`](https://www.npmjs.com/package/fast-text-encoding), but it seems it's not compatible with wasm-pack.
 - `copy-webpack-plugin` breaks when upgrading it to `^6.0.0`. This was only released 4 days ago, so it's not a big deal, but it seems it requires a change on how we configure it.
 - We have no CI whatsoever checking our WASM target, if I'm not mistaken, we should include a `wasm-pack test` command with maybe some tests to make sure that our WASM target builds and performs as expected.

**Comment by Razican** [comment]
This is ready for a merge!

**Comment by jasonwilliams** [comment]
> We have no CI whatsoever checking our WASM target, if I'm not mistaken, we should include a wasm-pack test command with maybe some tests to make sure that our WASM target builds and performs as expected.

Have you made an issue for this?

**Comment by Razican** [comment]
> > We have no CI whatsoever checking our WASM target, if I'm not mistaken, we should include a wasm-pack test command with maybe some tests to make sure that our WASM target builds and performs as expected.
> 
> Have you made an issue for this?

Yep, #408.

**Pull request merged**
