### PR TITLE
Fixed more Lexer Panics

### PR DESCRIPTION
**Pull request by adumbidiot**
I tried fixing more lexer panics. I think I got most of them. I think the errors could be better, but I think we should consider a new `LexerError` that includes file positions later on.

### CODE REVIEW

**Comment by jasonwilliams** [comment]
You able to rebase?

**Comment by adumbidiot** [comment]
Done

**Comment by adumbidiot** [comment]
Is that CI error my fault?

**Comment by jasonwilliams** [comment]
no, i have no idea why thats failing now

**Pull request merged**
