### PR TITLE
String match all fixes #115

### LINKED ISSUE #115: String.matchAll(regexp)
`matchAll` function would need to be added to the string object here:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/string.rs

It would be very similar to:
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/regexp.rs#L212-L251

Spec:
https://tc39.es/ecma262/#sec-string.prototype.matchAll

Notes:
https://github.com/jasonwilliams/boa/blob/master/docs/debugging.md

### PR DESCRIPTION
**Pull request by bojan88**
Implementation for #115.

Since `matchAll` is [part of RegExp prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/@@matchAll), and `String` objecti is calling it internally, I tried to follow that with my implementation.

There is still some work needed for `matchAll` to be finished. The method should return a JS iterator, but with this implementation it's returning an array. From what I understand, we don't have iterators implemented yet.

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Hi @bojan88 

Using [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll) as an example

```js
let regexp = /t(e)(st(\d?))/g;
let str = "test1test2";

str.matchAll(regexp)[0][1];
```
Should return 'e' instead i get 'undefined'

**Comment by bojan88** [comment]
Thanks.
I completely forgot to handle capture groups.
I will update the PR.

@jasonwilliams do you have any other requests or suggestions?

**Comment by jasonwilliams** [comment]
@bojan88 its looking ok to me, just the conflict now

**Comment by bojan88** [comment]
@jasonwilliams the conflict is fixed. Thanks.

**Pull request merged**
