### PR TITLE
Added a logo to the project.

### PR DESCRIPTION
**Pull request by HalidOdat**
No project is complete without a logo. So I made one, hope you like it and merge.

Here is the logo:
logo

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Wow!

Thank you 😊

**Comment by HalidOdat** [comment]
If you want me to make changes to the logo. Just say so :smile:

**Comment by jasonwilliams** [comment]
Do you have an SVG also?

**Comment by HalidOdat** [comment]
No i do not have it in a SVG format. But I will try to make it.

**Comment by jasonwilliams** [comment]
Thanks!

**Pull request merged**
