### PR TITLE
init string.replace work

### PR DESCRIPTION
**Pull request by louisgjohnson**
## TODO
Check it matches specs.
Add ability to pass function as second param.
Write some tests

### CODE REVIEW

**Comment by louisgjohnson** [comment]
BTW, for time writing rust so if I'm doing anything weird or wrong just let me know!

**Comment by jasonwilliams** [comment]
How is this going @louisgjohnson  ?

**Comment by louisgjohnson** [comment]
> How is this going @louisgjohnson ?

Hey sorry mate, I've been occupied with work and trying to learn some more rust. I'll just back onto this issue soon.

Is there any examples of how I would go about handling a JS function as a param?

**Comment by jasonwilliams** [comment]
@louisgjohnson 
> Is there any examples of how I would go about handling a JS function as a param?

Look at some of the array methods
https://github.com/jasonwilliams/boa/blob/master/src/lib/js/array.rs#L408-L436

**Comment by jasonwilliams** [comment]
This has now been added

**Pull request closed without merging**
